# fly.toml app configuration file generated for steexp on 2023-12-13T06:32:29+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "steexp"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 75
    soft_limit = 50

[[services]]
  protocol = ""
  internal_port = 0
  [services.concurrency]
    type = "connections"
    hard_limit = 75
    soft_limit = 50

[[services.ports]]
    handlers = ["http"]
    port = 3000

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "1m0s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/healthcheck"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
